#pragma once

//include iostream so we can std::cout things
#include <iostream>
//include string so we can use strings
#include <string>
//include filesystem and fstream so we can manage files
#include <filesystem>
#include <fstream>

//include associated OpenGL files
#include <glad/glad.h>
#include <GLFW/glfw3.h>

//include associated Dear ImGui files
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"

//now we include the files I made:
#include "CAD_SCENE.h"
#include "Shader.h"
#include "Message.h"

class CAD_APP
{
public:
	//constructor
	CAD_APP() {};
	//and destructor
	~CAD_APP();

	//we need a way to send/receive messages,
	//so we use our MessageManager
	static MessageManager messageManager;

	//"head" initialization function
	bool InitializeApp();

	//"head" main loop function
	void MainLoop();

	//returns if we want to close the window or not
	bool ShouldClose() { return glfwWindowShouldClose(this->applicationWindow); };

	//get pointers to the application window and the current scene
	GLFWwindow* GetMainWindow() { return this->applicationWindow; };
	CAD_SCENE* GetCurrentScene() { return this->currentScene; };

private:
	//pointers to the main window and current scene
	GLFWwindow* applicationWindow = nullptr;
	CAD_SCENE* currentScene = nullptr;

	//pointer to the application shader
	Shader* applicationShader = nullptr;

	//initialization functions
	bool InitializeGlfw();
	bool InitializeGlad();
	bool InitializeDearImGui();
	bool InitializeShader();
	void InitializeDirectories();

	//register callback "head" function
	//(happens in initialization)
	void RegisterCallbacks();
	//callback functions
	static void windowResizeCallback(GLFWwindow* resizedWindow, int newWidth, int newHeight);
	static void mouseButtonCallback(GLFWwindow* relevantWindow, int button, int action, int mods);
	static void mouseScrollCallback(GLFWwindow* relevantWindow, double xOffset, double yOffset);
	static void keyCallback(GLFWwindow* relevantWindow, int key, int scanCode, int action, int mods);
	
	//handle the processing of messages,
	//which are generated by callback functions
	void ProcessMessages();

	//start a new DearImgui frame
	void NewImGuiFrame();

	//update the application
	void Update();

	//render the application
	void Render();
	//render the openGL portion of
	//the application
	void RenderOpenGL();
	//render the DearImgui portion of
	//the application
	void RenderGUI();

	//load scene in various ways
	bool LoadSceneFromFile(std::string scenePath);
	CAD_SCENE* LoadEmptyScene();

	//shutdown the app
	void ShutdownApp();

};
